version: '3.8'

services:
  backend:
    build: ./backend
    container_name: pami-backend
    ports:
      - "8000:8000"
    volumes:
      - ./database:/app/database
    environment:
      - ENVIRONMENT=development